#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Tuple


class KGBackend(Protocol):
	name: str
	default_entity_prefix: Optional[str]

	def build_sparql_relations(self, query: str) -> str: ...

	def build_sparql_entities(self, query: str) -> str: ...

	def build_sparql_constraints(self, query: str) -> str: ...

	def build_sparql_constraint_pairs(self, query: str) -> str: ...

	def execute_sparql(self, sparql_txt: str) -> List[Dict[str, Any]]: ...

	def execute_sparql_with_meta(self, sparql_txt: str) -> Dict[str, Any]: ...

	def parse_relations(self, relations: List[Dict[str, Any]]) -> List[str]: ...

	def parse_entities(self, entities: List[Dict[str, Any]]) -> Tuple[List[str], List[str]]: ...

	def id2entity_name_or_type(self, entity_id: str) -> str: ...

	def id2entity_names(self, entity_ids: List[str]) -> Dict[str, str]: ...

	def is_unnecessary_relation(self, relation: str) -> bool: ...

	def normalize_uri(self, value: str) -> str: ...

	def is_entity_id(self, value: str) -> bool: ...

	def relation_id2label(self, relation_id: str) -> str: ...

	def relation_ids2labels(self, relation_ids: List[str]) -> Dict[str, str]: ...

	def format_entity_node(self, entity_id: str) -> str: ...

	def format_relation_node(self, relation_id: str) -> str: ...
